In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import re
import string
import nltk
import spacy

In [5]:
df_fake=pd.read_csv("Fake.csv")
df_true=pd.read_csv("True.csv")

In [6]:
df_fake.head(5)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [7]:
df_true.head(5)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
df_fake.shape,df_true.shape

((23481, 4), (21417, 4))

In [9]:
df_true['class']=1
df_fake['class']=0

In [10]:
df_fake.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [11]:
df_true.head(10)

,title,text,subject,date,class
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017",1
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017",1
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017",1

In [12]:
df_merged=pd.concat([df_fake,df_true],axis=0)
df_merged.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [13]:
df_merged.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [14]:
df=df_merged.drop(['title','subject','date'],axis=1)
df.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [15]:
df.isna().sum()

text     0
class    0
dtype: int64

In [16]:
df=df.sample(frac=1)
df.head()

                                                    text  class
18350  RIYADH (Reuters) - Saudi Arabia s King Salman ...      1
8609   PHILADELPHIA (Reuters) - New York media mogul ...      1
1753   Welcome to the big leagues, kid.Donald Trump s...      0
21328  YANGON (Reuters) - Muslim militants in Myanmar...      1
5770   (Reuters) - A federal judge in Florida on Wedn...      1

In [17]:
df.reset_index(inplace=True)
df.drop(["index"], axis = 1, inplace = True)

In [18]:
df.head()

                                                text  class
0  RIYADH (Reuters) - Saudi Arabia s King Salman ...      1
1  PHILADELPHIA (Reuters) - New York media mogul ...      1
2  Welcome to the big leagues, kid.Donald Trump s...      0
3  YANGON (Reuters) - Muslim militants in Myanmar...      1
4  (Reuters) - A federal judge in Florida on Wedn...      1

In [19]:
from nltk_utils import *

In [20]:
def wordopt(text):
    if text is None:
        return ""
    text=upper_to_lower(text)
    text=remove_punctuation(text)
    text=remove_stopwords(text)
    text=remove_freqwords(text)
    text=remove_rarewords(text)
    text=lematization(text)
    text=remove_emoji(text)
    text=remove_urls(text)
    text=remove_html(text)
    return text

df['text']=df['text'].apply(lambda x: wordopt(x))
df.head(5)

                                                text  class
0  riyadh reuters saudi arabia king salman left w...      1
1  philadelphia reuters new york medium mogul mic...      1
2  welcome big league kiddonald trump supreme cou...      0
3  yangon reuters muslim militant myanmar staged ...      1
4  reuters federal judge florida wednesday direct...      1

In [21]:
x=df['text']
y=df['class']

In [22]:
x.size,y.size

(44898, 44898)

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
xv_train=vectorizer.fit_transform(x_train)
xv_test=vectorizer.transform(x_test)

In [25]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [26]:
model_lr=lr.fit(xv_train,y_train)

In [27]:
train_pred_lr=model_lr.predict(xv_train)
print(f"Training Score Accuracy for Logistic Regression Model : ",accuracy_score(train_pred_lr,y_train))

Training Score Accuracy for Logistic Regression Model :  0.9931696017580851

In [28]:
test_pred_lr=model_lr.predict(xv_test)
print(f"Training Score Accuracy for Logistic Regression Model : ",accuracy_score(test_pred_lr,y_test))

Training Score Accuracy for Logistic Regression Model :  0.9893986636971047

In [29]:
conf_lr=confusion_matrix(y_test,test_pred_lr)
print(conf_lr)

[[5755   70]
 [  49 5351]]

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, test_pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5825
           1       0.99      0.99      0.99      5400

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225

In [31]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
model_dt=dt.fit(xv_train,y_train)

In [32]:
train_pred_dt=model_dt.predict(xv_train)
print(f"Training Score Accuracy for Logistic Regression Model : ",accuracy_score(train_pred_dt,y_train))

Training Score Accuracy for Logistic Regression Model :  0.9999703026163395

In [33]:
test_pred_dt=model_dt.predict(xv_test)
print(f"Testing Score Accuracy for Logistic Regression Model : ",accuracy_score(test_pred_dt,y_test))

Testing Score Accuracy for Logistic Regression Model :  0.9976837416481069

In [34]:
conf_dt=confusion_matrix(y_test,test_pred_dt)
print(conf_dt)

[[5809   16]
 [  10 5390]]

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, test_pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5825
           1       1.00      1.00      1.00      5400

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

In [36]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(random_state=0)

In [37]:
model_gb=gb.fit(xv_train,y_train)

In [38]:
train_pred_gb=model_dt.predict(xv_train)
print(f"Training Score Accuracy for Logistic Regression Model : ",accuracy_score(train_pred_gb,y_train))

Training Score Accuracy for Logistic Regression Model :  0.9999703026163395

In [39]:
test_pred_gb=model_dt.predict(xv_test)
print(f"Testing Score Accuracy for Logistic Regression Model : ",accuracy_score(test_pred_gb,y_test))

Testing Score Accuracy for Logistic Regression Model :  0.9976837416481069

In [40]:
conf_gb=confusion_matrix(y_test,test_pred_gb)
print(conf_gb)

[[5809   16]
 [  10 5390]]

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test, test_pred_gb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5825
           1       1.00      1.00      1.00      5400

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

In [42]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=0)
model_rf=rf.fit(xv_train,y_train)

In [43]:
train_pred_rf=model_rf.predict(xv_train)
print(f"Training Score Accuracy for Logistic Regression Model : ",accuracy_score(train_pred_rf,y_train))

Training Score Accuracy for Logistic Regression Model :  0.9999703026163395

In [44]:
test_pred_rf=model_rf.predict(xv_test)
print(f"Testing Score Accuracy for Logistic Regression Model : ",accuracy_score(test_pred_rf,y_test))

Testing Score Accuracy for Logistic Regression Model :  0.9921603563474387

In [45]:
conf_rf=confusion_matrix(y_test,test_pred_rf)
print(conf_rf)

[[5758   67]
 [  21 5379]]

In [46]:
print(classification_report(y_test, test_pred_rf))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      5825
           1       0.99      1.00      0.99      5400

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225

In [49]:
def output_lable(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"
    
def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt) 
    new_x_test = new_def_test["text"]
    new_xv_test = vectorizer.transform(new_x_test)
    pred_lr = model_lr.predict(new_xv_test)
    pred_dt = model_dt.predict(new_xv_test)
    pred_gb = model_gb.predict(new_xv_test)
    pred_rf = model_rf.predict(new_xv_test)

    return print("\n\nLR Prediction: {} \nDT Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(output_lable(pred_lr[0]),output_lable(pred_dt[0]), output_lable(pred_gb[0]), output_lable(pred_rf[0])))

In [50]:
news = "BRUSSELS (Reuters) - NATO allies on Tuesday welcomed President Donald Trump s decision to commit more forces to Afghanistan, as part of a new U.S. strategy he said would require more troops and funding from America s partners. Having run for the White House last year on a pledge to withdraw swiftly from Afghanistan, Trump reversed course on Monday and promised a stepped-up military campaign against  Taliban insurgents, saying:  Our troops will fight to win .  U.S. officials said he had signed off on plans to send about 4,000 more U.S. troops to add to the roughly 8,400 now deployed in Afghanistan. But his speech did not define benchmarks for successfully ending the war that began with the U.S.-led invasion of Afghanistan in 2001, and which he acknowledged had required an   extraordinary sacrifice of blood and treasure .  We will ask our NATO allies and global partners to support our new strategy, with additional troops and funding increases in line with our own. We are confident they will,  Trump said. That comment signaled he would further increase pressure on U.S. partners who have already been jolted by his repeated demands to step up their contributions to NATO and his description of the alliance as  obsolete  - even though, since taking office, he has said this is no longer the case. NATO Secretary General Jens Stoltenberg said in a statement:  NATO remains fully committed to Afghanistan and I am looking forward to discussing the way ahead with (Defense) Secretary (James) Mattis and our Allies and international partners.  NATO has 12,000 troops in Afghanistan, and 15 countries have pledged more, Stoltenberg said. Britain, a leading NATO member, called the U.S. commitment  very welcome .  In my call with Secretary Mattis yesterday we agreed that despite the challenges, we have to stay the course in Afghanistan to help build up its fragile democracy and reduce the terrorist threat to the West,  Defence Secretary Michael Fallon said. Germany, which has borne the brunt of Trump s criticism over  the scale of its defense spending, also welcomed the new U.S. plan.  Our continued commitment is necessary on the path to stabilizing the country,  a government spokeswoman said. In June, European allies had already pledged more troops but had not given details on numbers, waiting for the Trump administration to outline its strategy for the region.Nearly 16 years after the U.S.-led invasion - a response to the Sept. 11 attacks which were planned by al Qaeda leader Osama bin Laden from Afghanistan - the country is still struggling with weak central government and a Taliban insurgency. Trump said he shared the frustration of the American people who were  weary of war without victory , but a hasty withdrawal would create a vacuum for groups like Islamic State and al Qaeda to fill."

manual_testing(news)

LR Prediction: Not A Fake News
DT Prediction: Not A Fake News
GBC Prediction: Not A Fake News
RFC Prediction: Not A Fake News

In [54]:
import joblib

joblib.dump(model_lr,'LogicticRegression_model.pkl')
joblib.dump(model_dt,'DecisionTree_model.pkl')
joblib.dump(model_gb,'GradientBoosting_model.pkl')
joblib.dump(model_rf,'RandomForest_model.pkl')
joblib.dump(vectorizer,'Vectorizer.pkl')

['Vectorizer.pkl']